title: "wilhelm codes"
description: "I code here and do other things."
url: "https://wilhelm.codes"
feed_limit: 15
author: "blitzkriegpunk"
serve_port: 3000

paths:
  root: "dist"
  posts: "posts"
  authors: "authors"
  tags: "tags"
  templates: "templates"

mappings:
  - type: "index"
    input: "index.tpl"
    partials:
      - "partials/head.tpl"
      - "partials/footer.tpl"
      - "partials/card.tpl"
      - "partials/tags.tpl"
      - "partials/recent.tpl"

  - type: "author"
    input: "author.tpl"
    partials:
      - "partials/head.tpl"
      - "partials/footer.tpl"

  - type: "post"
    input: "post.tpl"
    partials:
      - "partials/head.tpl"
      - "partials/footer.tpl"

  - type: "tag"
    input: "tag.tpl"
    partials:
      - "partials/head.tpl"
      - "partials/footer.tpl"

  - type: "page"
    input: "tags.tpl"
    output: "tags/index.html"

  - type: "page"
    input: "about.tpl"
    output: "about/index.html"
    
  - type: "page"
    input: "posts.tpl"
    output: "posts/index.html"