title: "wilhelm codes"
description: "I code here and do other things."
url: "https://wilhelm.codes"
feed_limit: 15
author: "blitzkriegpunk"

paths:
  root: "dist"
  feeds: "feeds"
  posts: "posts"
  authors: "authors"
  tags: "tags"
  templates: "templates"

mappings:
  # - type: "post"
  #   input: "post.tpl"
  #   partials:
  #     - "partials/head.tpl"
  #     - "partials/footer.tpl"
  # - type: "tag"
  #   input: "tags.tpl"
  #   output: "tags/index.html"
  #   partials:
  #     - "partials/head.tpl"
  #     - "partials/footer.tpl"
  - type: "index"
    input: "index.tpl"
    output: "index.html"
    partials:
      - "partials/head.tpl"
      - "partials/footer.tpl"
      - "partials/card.tpl"
      - "partials/tags.tpl"
      - "partials/recent.tpl"