directories:
  articles: "../dist/data/articles"
  tags: "../dist/data/tags"
  authors: "../dist/data/authors"
  templates: "../dist/templates"
  static: "../dist"
  images: "../dist/images"

index:
  input: "index.tpl"
  output: "index.html"
  sources:
    - "tags/index.json"
    - "articles/index.json"
    - "authors/index.json"
  partials:
    - "header.tpl"
    - "footer.tpl"
    - "wrapper.tpl"